

services:
  catatkredit:
    build: .
    container_name: catatkredit-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - catatkredit_data:/app/data
    environment:
      - NODE_ENV=production
      - SQLITE_DB_PATH=/app/data/catatbon.db

volumes:
  catatkredit_data:
